import mutations from './mutations.js';
import actions from './actions.js';
import getters from './getters.js';

export default {
    namespaced: true,
    state() {
        return {
            flightInfos: [
                {
                    id: 1,
                    name: 'Pegasus',
                    img: "https://cdn.enuygun.com/ucak-bileti/v-dd142/assets/images/airline-icon/PC.png",
                    date: '17.10.2023',      // Format date'de ay ve gün yeri değişiyor. Çünkü burada yanlış 
                    from: 'Mardin',
                    to: 'İzmir',
                    city_code_from: 'MQM',  
                    city_code_to: 'ADB',
                    departureTime: '9.20',
                    arrivalTime: '11.20',
                    price: 1650,
                    numberOfBookableSeats: 10,  // (total of classes left)
                    economy: 3,
                    business: 5,
                    firstClass: 2
                },
                {
                    id: 2,
                    name: 'THY',
                    img: "https://cdn.enuygun.com/ucak-bileti/v-dd142/assets/images/airline-icon/TK.png",
                    date: '10.10.2023',
                    from: 'Mardin',
                    to: 'İzmir',
                    city_code_from: 'MQM',
                    city_code_to: 'ADB',
                    departureTime: '12.00',
                    arrivalTime: '14.15',
                    price: 3010,
                    numberOfBookableSeats: 10,  
                    economy: 3,
                    business: 5,
                    firstClass: 2
                },
                {
                    id: 90,
                    name: 'Sun Express',
                    img: "https://cdn.enuygun.com/ucak-bileti/v-68eca/assets/images/airline-icon/XQ.png",
                    date: '10.10.2023',
                    from: 'Mardin',
                    to: 'İzmir',
                    city_code_from: 'MQM',
                    city_code_to: 'ADB',
                    departureTime: '02.00',
                    arrivalTime: '14.05',
                    price: 3000,
                    numberOfBookableSeats: 10,  
                    economy: 3,
                    business: 5,
                    firstClass: 2
                }, 
                {
                    id: 91,
                    name: 'THY',
                    img: "https://cdn.enuygun.com/ucak-bileti/v-dd142/assets/images/airline-icon/TK.png",
                    date: '10.10.2023',
                    from: 'Mardin',
                    to: 'İzmir',
                    city_code_from: 'MQM',
                    city_code_to: 'ADB',
                    departureTime: '03.00',
                    arrivalTime: '15.15',
                    price: 2000,
                    numberOfBookableSeats: 10,  
                    economy: 3,
                    business: 5,
                    firstClass: 2
                }, 
                {
                    id: 92,
                    name: 'THY',
                    img: "https://cdn.enuygun.com/ucak-bileti/v-dd142/assets/images/airline-icon/TK.png",
                    date: '10.10.2023',
                    from: 'Mardin',
                    to: 'İzmir',
                    city_code_from: 'MQM',
                    city_code_to: 'ADB',
                    departureTime: '04.00',
                    arrivalTime: '14.00',
                    price: 1000,
                    numberOfBookableSeats: 10,  
                    economy: 3,
                    business: 5,
                    firstClass: 2
                },  
                {
                    id: 93,
                    name: 'THY',
                    img: "https://cdn.enuygun.com/ucak-bileti/v-dd142/assets/images/airline-icon/TK.png",
                    date: '10.10.2023',
                    from: 'Mardin',
                    to: 'İzmir',
                    city_code_from: 'MQM',
                    city_code_to: 'ADB',
                    departureTime: '05.00',
                    arrivalTime: '10.40',
                    price: 1170,
                    numberOfBookableSeats: 10,  
                    economy: 3,
                    business: 5,
                    firstClass: 2
                }, 
                {
                    id: 3,
                    name: 'THY',
                    img: "https://cdn.enuygun.com/ucak-bileti/v-dd142/assets/images/airline-icon/TK.png",
                    date: '10.10.2023',
                    from: 'Mardin',
                    to: 'İstanbul',
                    city_code_from: 'MQM',
                    city_code_to: 'SAW',
                    departureTime: '19.15',
                    arrivalTime: '21.30',
                    price: 5200,
                    numberOfBookableSeats: 10,  
                    economy: 3,
                    business: 5,
                    firstClass: 2
                },
                {
                    id: 4,
                    name: 'THY',
                    img: "https://cdn.enuygun.com/ucak-bileti/v-dd142/assets/images/airline-icon/TK.png",
                    date: '10.10.2023',
                    from: 'Mardin',
                    to: 'Ankara',
                    city_code_from: 'MQM',
                    city_code_to: 'ESB',
                    departureTime: '15.55',
                    arrivalTime: '16.40',
                    price: 1500,
                    numberOfBookableSeats: 10,  
                    economy: 3,
                    business: 5,
                    firstClass: 2
                },
                {
                    id: 5,
                    name: 'THY',
                    img: "https://cdn.enuygun.com/ucak-bileti/v-dd142/assets/images/airline-icon/TK.png",
                    date: '10.10.2023',
                    from: 'İstanbul',
                    to: 'İzmir',
                    city_code_from: 'SAW',
                    city_code_to: 'ADB',
                    departureTime: '23.30',
                    arrivalTime: '00.15',
                    price: 1200,
                    numberOfBookableSeats: 10,  
                    economy: 3,
                    business: 5,
                    firstClass: 2
                },
                {
                    id: 65,
                    name: 'THY',
                    img: "https://cdn.enuygun.com/ucak-bileti/v-dd142/assets/images/airline-icon/TK.png",
                    date: '10.10.2023',
                    from: 'İstanbul',
                    to: 'İzmir',
                    city_code_from: 'SAW',
                    city_code_to: 'ADB',
                    departureTime: '23.30',
                    arrivalTime: '02.20',
                    price: 1000,
                    numberOfBookableSeats: 10,  
                    economy: 3,
                    business: 5,
                    firstClass: 2
                },
                {
                    id: 66,
                    name: 'Pegasus',
                    img: "https://cdn.enuygun.com/ucak-bileti/v-dd142/assets/images/airline-icon/PC.png",
                    date: '10.10.2023',
                    from: 'İstanbul',
                    to: 'İzmir',
                    city_code_from: 'SAW',
                    city_code_to: 'ADB',
                    departureTime: '22.40',
                    arrivalTime: '23.55',
                    price: 1400,
                    numberOfBookableSeats: 10,  
                    economy: 3,
                    business: 5,
                    firstClass: 2
                },
                {
                    id: 6,
                    name: 'Sun Express',
                    img: "https://cdn.enuygun.com/ucak-bileti/v-68eca/assets/images/airline-icon/XQ.png",
                    date: '10.10.2023',
                    from: 'Ankara',
                    to: 'İzmir',
                    city_code_from: 'ESB',
                    city_code_to: 'ADB',
                    departureTime: '20.30',
                    arrivalTime: '21.15',
                    price: 3500,
                    numberOfBookableSeats: 10,  
                    economy: 3,
                    business: 5,
                    firstClass: 2
                },
                {
                    id: 7,
                    name: 'Sun Express',
                    img: "https://cdn.enuygun.com/ucak-bileti/v-68eca/assets/images/airline-icon/XQ.png",
                    date: '11.10.2023',
                    from: 'Ankara',
                    to: 'İzmir',
                    city_code_from: 'ESB',
                    city_code_to: 'ADB',
                    departureTime: '01.10',
                    arrivalTime: '03.05',
                    price: 3610,
                    numberOfBookableSeats: 10,  
                    economy: 3,
                    business: 5,
                    firstClass: 2
                },
                {
                    id: 8,
                    name: 'Sun Express',
                    img: "https://cdn.enuygun.com/ucak-bileti/v-68eca/assets/images/airline-icon/XQ.png",
                    date: '09.10.2023',
                    from: 'Ankara',
                    to: 'İzmir',
                    city_code_from: 'ESB',
                    city_code_to: 'ADB',
                    departureTime: '20.30',
                    arrivalTime: '21.55',
                    price: 3160,
                    numberOfBookableSeats: 10,  
                    economy: 3,
                    business: 5,
                    firstClass: 2
                },
                {
                    id: 9,
                    name: 'Sun Express',
                    img: "https://cdn.enuygun.com/ucak-bileti/v-68eca/assets/images/airline-icon/XQ.png",
                    date: '10.10.2023',
                    from: 'Adana',
                    to: 'İzmir',
                    city_code_from: 'ADA',
                    city_code_to: 'ADB',
                    departureTime: '9.20',
                    arrivalTime: '11.20',
                    price: 2000,
                    numberOfBookableSeats: 10,  
                    economy: 3,
                    business: 5,
                    firstClass: 2
                },
                {
                    id: 10,
                    name: 'Sun Express',
                    img: "https://cdn.enuygun.com/ucak-bileti/v-68eca/assets/images/airline-icon/XQ.png",
                    date: '10.10.2023',
                    from: 'Trabzon',
                    to: 'Kars',
                    city_code_from: 'TZX',
                    city_code_to: 'KSY',
                    departureTime: '9.20',
                    arrivalTime: '11.20',
                    price: 2200,
                    numberOfBookableSeats: 10,  
                    economy: 3,
                    business: 5,
                    firstClass: 2
                },
                {
                    id: 11,
                    name: 'Sun Express',
                    img: "https://cdn.enuygun.com/ucak-bileti/v-68eca/assets/images/airline-icon/XQ.png",
                    date: '10.10.2023',
                    from: 'İstanbul',
                    to: 'Ankara',
                    city_code_from: 'SAW',
                    city_code_to: 'ESB',
                    departureTime: '16.40',
                    arrivalTime: '17.50',
                    price: 2010,
                    numberOfBookableSeats: 10,  
                    economy: 3,
                    business: 5,
                    firstClass: 2
                },
                {
                    id: 12,
                    name: 'Pegasus',
                    img: "https://cdn.enuygun.com/ucak-bileti/v-dd142/assets/images/airline-icon/PC.png",
                    date: '10.10.2023',
                    from: 'İstanbul',
                    to: 'Ankara',
                    city_code_from: 'SAW',
                    city_code_to: 'ESB',
                    departureTime: '21.50',
                    arrivalTime: '00.15',
                    price: 2201,
                    numberOfBookableSeats: 10,  
                    economy: 3,
                    business: 5,
                    firstClass: 2
                },
                {
                    id: 12,
                    name: 'Pegasus',
                    img: "https://cdn.enuygun.com/ucak-bileti/v-dd142/assets/images/airline-icon/PC.png",
                    date: '10.10.2023',
                    from: 'İstanbul',
                    to: 'Ankara',
                    city_code_from: 'SAW',
                    city_code_to: 'ESB',
                    departureTime: '21.50',
                    arrivalTime: '02.05',
                    price: 2000,
                    numberOfBookableSeats: 10,  
                    economy: 3,
                    business: 5,
                    firstClass: 2
                },
                {
                    id: 13,
                    name: 'Pegasus',
                    img: "https://cdn.enuygun.com/ucak-bileti/v-dd142/assets/images/airline-icon/PC.png",
                    date: '09.10.2023',
                    from: 'İstanbul',
                    to: 'Ankara',
                    city_code_from: 'SAW',
                    city_code_to: 'ESB',
                    departureTime: '22.50',
                    arrivalTime: '23.25',
                    price: 2000,
                    numberOfBookableSeats: 10,  
                    economy: 3,
                    business: 5,
                    firstClass: 2
                }
            ],

            chosenFlightNormal: [],
            chosenFlightConnecting: [],
            mergedChosenConnecting: [],
            formatDate: null
        }
    },
    mutations,
    actions,
    getters
};
